version: '3.8'

services:
  cabm:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_NAME:-cabm}:${DOCKER_IMAGE_TAG:-latest}
    container_name: cabm-app
    ports:
      - "${FLASK_PORT:-5000}:5000"
    environment:
      # 从.env.docker文件读取环境变量
      - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
      - FLASK_PORT=5000
      - FLASK_DEBUG=${FLASK_DEBUG:-false}
      # API配置
      - CHAT_API_BASE_URL=${CHAT_API_BASE_URL}
      - CHAT_API_KEY=${CHAT_API_KEY}
      - CHAT_MODEL=${CHAT_MODEL}
      - IMAGE_API_BASE_URL=${IMAGE_API_BASE_URL}
      - IMAGE_API_KEY=${IMAGE_API_KEY}
      - IMAGE_MODEL=${IMAGE_MODEL}
      - EMBEDDING_API_BASE_URL=${EMBEDDING_API_BASE_URL}
      - EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - OPTION_API_BASE_URL=${OPTION_API_BASE_URL}
      - OPTION_API_KEY=${OPTION_API_KEY}
      - OPTION_MODEL=${OPTION_MODEL}
    volumes:
      # 持久化数据目录
      - ./data:/app/data
      - ./static/images:/app/static/images
      # 可选：挂载配置文件（如果需要自定义配置）
      - ./config.py:/app/config.py:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: cabm-network
